-- MySQL Script generated by MySQL Workbench
-- Sun Jan 28 23:03:24 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema learnsong
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema learnsong
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `learnsong` DEFAULT CHARACTER SET utf8 ;
USE `learnsong` ;

-- -----------------------------------------------------
-- Table `learnsong`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `learnsong`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `active` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `modify_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `learnsong`.`countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `learnsong`.`countries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `active` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `modify_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `learnsong`.`singers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `learnsong`.`singers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `active` VARCHAR(45) NOT NULL,
  `meta` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NOT NULL,
  `modify_at` TIMESTAMP NULL,
  `avatar` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `learnsong`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `learnsong`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `active` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `learnsong`.`songs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `learnsong`.`songs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `active` VARCHAR(45) NOT NULL,
  `categories_id` INT NOT NULL,
  `singers_id` INT NOT NULL,
  `source_audio` MEDIUMTEXT NOT NULL,
  `source_lyric` MEDIUMTEXT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `modify_at` TIMESTAMP NULL,
  `meta` TEXT NULL,
  `image` MEDIUMTEXT NOT NULL,
  `thumb` MEDIUMTEXT NOT NULL,
  `countries_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_songs_categories1_idx` (`categories_id` ASC),
  INDEX `fk_songs_singeres1_idx` (`singers_id` ASC),
  INDEX `fk_songs_countries1_idx` (`countries_id` ASC),
  CONSTRAINT `fk_songs_categories1`
    FOREIGN KEY (`categories_id`)
    REFERENCES `learnsong`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_songs_singeres1`
    FOREIGN KEY (`singers_id`)
    REFERENCES `learnsong`.`singers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_songs_countries1`
    FOREIGN KEY (`countries_id`)
    REFERENCES `learnsong`.`countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `learnsong`.`cover_songs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `learnsong`.`cover_songs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `source_audio` VARCHAR(45) NOT NULL,
  `active` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `modify_at` TIMESTAMP NULL,
  `users_id` INT NOT NULL,
  `songs_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cover_songs_users1_idx` (`users_id` ASC),
  INDEX `fk_cover_songs_songs1_idx` (`songs_id` ASC),
  CONSTRAINT `fk_cover_songs_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `learnsong`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cover_songs_songs1`
    FOREIGN KEY (`songs_id`)
    REFERENCES `learnsong`.`songs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
